from os import path, mkdir

def createMissingFiles(dir = "."):
    if not path.exists("task2/not_existing.txt"):
        print("Not existing files list not found. Run task2.py first")
        return
    with open("task2/not_existing.txt", "r") as arr:
        files = arr.read().split("\n")
        if not path.exists(dir):
            mkdir(dir)
        for f in files:
            filePath = path.join(dir, f)
            with open(filePath, "w") as out:
                out.write("Generated by task3.py")



dir = str(input("Enter directory name for creating missing files: "))
createMissingFiles(dir)